name: Build and Deploy Thesis for University

on: 
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Thesis for University
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python v3
        uses: actions/setup-python@v3
        with:
          distribution: 'corretto'
          python-version: 3.10

      - name: Unit Tests
        run: mvn -B test --file alien.invasion.py

      - name: Build the Thesis
        run: |
          mvn clean
          mvn -B package --file alien.invasion.py