name: Build and Deploy Thesis for University

on: 
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Thesis for University
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python v3
        uses: actions/setup-python@v3
        with:
          distribution: 'corretto'
          python-version: 3.10

      # - name: Unit Tests
      #   run: mvn -B test --file alien.invasion.py

      - name: Build the Thesis
        run: |
          mvn clean
          mvn -B package --file alien.invasion.py

      - name: Build Docker Image
        uses: docker/build=push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/thesis:$(date- '%Y%m%d%H%M%S')
      -name: Login to Docker Hub
       uses: docker/login-action@v1
       with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/thesis:$(date- '%Y%m%d%H%M%S')