name: Build and Deploy Thesis for University

on: 
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Thesis for University
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file alien.invasion.py

      - name: Build the Thesis
        run: |
          mvn clean
          mvn -B package --file alien.invasion.py